"""Chart data layer.

Every chart drawn by `ui/*.py` gets its series built here instead of inside the
Streamlit render function. A builder answers two questions the UI must not:

* *what should be drawn* — aggregation, state mapping, transition compression,
  time-series ordering; and
* *whether there is anything to draw* — reported as an explicit status the UI
  translates into `st.info` / `st.success` / silence.

The UI keeps only plotly styling: colors, labels, heights, hover templates.

Builders are pure functions, so `ui/*.py` imports them directly rather than
going through an HTTP endpoint (see `plm/service.py` for the same rule): a
Streamlit rerun must not pay a round trip to redraw a chart.
"""

from .boot import (
    DATA_READY_PATTERN,
    SLOW_EVENT_LIMIT,
    VOICE_READY_PATTERN,
    BootMilestones,
    BootSequence,
    build_boot_sequence,
)
from .crash import (
    BINDER_EVENT_DISPLAY_CAP,
    BINDER_EVENT_TYPES,
    BINDER_PROXY_LEAK_THRESHOLD,
    SYSTEM_EVENT_TYPES,
    AnrEvent,
    AnrLockChain,
    AnrSummary,
    BinderEvents,
    BinderProxyHistogram,
    BinderSpamEvent,
    CrashOverview,
    JavaCrash,
    NativeCrash,
    SystemWtfSummary,
    build_binder_events,
    build_binder_proxy_histograms,
    build_crash_overview,
    build_system_kills,
    build_system_wtf_summary,
    normalize_anr_list,
)
from .network import (
    DNS_SPIKE_THRESHOLD_MS,
    DNS_SUCCESS_CODES,
    INTERNET_STALL_LAYER_TABS,
    DataUsageProfile,
    DnsErrorBreakdown,
    DnsHealthWarning,
    DnsIssueSummary,
    InternetStallKpi,
    InternetStallReport,
    LayerTab,
    LayerView,
    MetricOption,
    NetworkTimelineStats,
    StallWindow,
    build_data_usage_profile,
    build_dns_error_breakdown,
    build_dns_health_warnings,
    build_dns_issue_summary,
    build_internet_stall_report,
    build_network_timeline_stats,
)
from .power import (
    THERMAL_WARNING_C,
    PowerPanelSection,
    PowerThermalPanel,
    build_power_thermal_panel,
)
from .satellite import (
    ICON_OFF,
    ICON_ON_HYSTERESIS,
    ICON_ON_REAL,
    NTN_EVENT_ORDER,
    NtnOverview,
    NtnStatus,
    build_ntn_overview,
)
from .telephony import (
    RILJ_SLOW_THRESHOLD_MS,
    SERVICE_STATE_ORDER,
    UTC_GEO_MAP,
    CallHistorySummary,
    CallSpan,
    DataCallKpi,
    DataCallSummary,
    NitzGeoPoint,
    NitzKpi,
    NitzOffsetPoint,
    NitzTimeline,
    RfCallTimeline,
    RiljKpi,
    RiljOverview,
    RsrpPoint,
    ServiceStatePoint,
    ServiceStateSeries,
    SignalLevelPoint,
    SignalLevelSeries,
    SipErrorMarker,
    SipFlow,
    SipFlowKpi,
    SipMessage,
    build_call_history_summary,
    build_data_call_summary,
    build_nitz_timeline,
    build_rf_call_timeline,
    build_rilj_overview,
    build_service_state_series,
    build_signal_level_series,
    build_sip_flow,
    map_registration_state,
)

__all__ = [
    "DATA_READY_PATTERN",
    "SLOW_EVENT_LIMIT",
    "VOICE_READY_PATTERN",
    "BootMilestones",
    "BootSequence",
    "build_boot_sequence",
    "BINDER_EVENT_DISPLAY_CAP",
    "BINDER_EVENT_TYPES",
    "BINDER_PROXY_LEAK_THRESHOLD",
    "ICON_OFF",
    "ICON_ON_HYSTERESIS",
    "ICON_ON_REAL",
    "NTN_EVENT_ORDER",
    "SYSTEM_EVENT_TYPES",
    "THERMAL_WARNING_C",
    "AnrEvent",
    "AnrLockChain",
    "AnrSummary",
    "BinderEvents",
    "BinderProxyHistogram",
    "BinderSpamEvent",
    "CrashOverview",
    "JavaCrash",
    "NativeCrash",
    "NtnOverview",
    "NtnStatus",
    "PowerPanelSection",
    "PowerThermalPanel",
    "SystemWtfSummary",
    "build_binder_events",
    "build_binder_proxy_histograms",
    "build_crash_overview",
    "build_ntn_overview",
    "build_power_thermal_panel",
    "build_system_kills",
    "build_system_wtf_summary",
    "normalize_anr_list",
    "DNS_SPIKE_THRESHOLD_MS",
    "DNS_SUCCESS_CODES",
    "INTERNET_STALL_LAYER_TABS",
    "DataUsageProfile",
    "DnsErrorBreakdown",
    "DnsHealthWarning",
    "DnsIssueSummary",
    "InternetStallKpi",
    "InternetStallReport",
    "LayerTab",
    "LayerView",
    "MetricOption",
    "NetworkTimelineStats",
    "StallWindow",
    "build_data_usage_profile",
    "build_dns_error_breakdown",
    "build_dns_health_warnings",
    "build_dns_issue_summary",
    "build_internet_stall_report",
    "build_network_timeline_stats",
    "RILJ_SLOW_THRESHOLD_MS",
    "SERVICE_STATE_ORDER",
    "UTC_GEO_MAP",
    "CallHistorySummary",
    "CallSpan",
    "DataCallKpi",
    "DataCallSummary",
    "NitzGeoPoint",
    "NitzKpi",
    "NitzOffsetPoint",
    "NitzTimeline",
    "RfCallTimeline",
    "RiljKpi",
    "RiljOverview",
    "RsrpPoint",
    "ServiceStatePoint",
    "ServiceStateSeries",
    "SignalLevelPoint",
    "SignalLevelSeries",
    "SipErrorMarker",
    "SipFlow",
    "SipFlowKpi",
    "SipMessage",
    "build_call_history_summary",
    "build_data_call_summary",
    "build_nitz_timeline",
    "build_rf_call_timeline",
    "build_rilj_overview",
    "build_service_state_series",
    "build_signal_level_series",
    "build_sip_flow",
    "map_registration_state",
]
